{{- if and .Values.testing.aktoApiSecurityTesting.env.useSecretsForDatabaseAbstractorToken (not .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.existingSecret) .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-mini-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.testing.aktoApiSecurityTesting.env.databaseAbstractorTokenSecrets.token | toString | b64enc | quote }}
{{- end }}