{{ if and .Values.testing.autoScaling.enabled .Values.testing.grafanaCloud.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testing.grafanaCloud.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ quote .Values.testing.grafanaCloud.username }}
  readToken: {{ quote .Values.testing.grafanaCloud.readToken }}
{{ end }}
