apiVersion: v2
name: akto-ai-guardrails
description: Helm chart for installing Akto AI Guardrails services
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/akto-ai-guardrails
keywords:
  - akto
  - ai
  - guardrails
  - security
  - llm
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
