apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-cloud-setup.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-cloud-setup.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "grafanaCloud.username is required" .Values.grafanaCloud.username | quote }}
  writeToken: {{ required "grafanaCloud.writeToken is required" .Values.grafanaCloud.writeToken | quote }}
