{{- if .Values.alloy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-cloud-setup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-cloud-setup.labels" . | nindent 4 }}
{{- end }}
