apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto.fullname" . }}-threat-backend
  labels:
  {{- include "akto.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: {{ .Values.threat_backend.type }}
  selector:
    app: {{ include "akto.fullname" . }}-threat-backend
  {{- include "akto.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.threat_backend.ports | toYaml | nindent 2 -}}