apiVersion: v2
name: akto-dbabs
description: Helm chart for installing Akto
type: application
version: 0.1.4
appVersion: "0.1.4"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/akto-setup-database-abstractor
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io