apiVersion: v2
name: data-ingestion-service
description: Helm chart for Akto Data Ingestion Service
type: application
version: 0.1.3
appVersion: "0.1.3"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/data-ingestion-service
keywords:
  - akto
  - api
  - api security
  - data ingestion
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
