apiVersion: v2
name: akto-mini-testing
description: Helm chart for installing Akto hybrid testing
type: application
version: 1.43.8
appVersion: "1.43.8"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/mini-testing
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
