{{- if .Values.agentGuardExecutor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto-ai-guardrails.fullname" . }}-executor
  labels:
    {{- include "akto-ai-guardrails.agentGuardExecutor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agentGuardExecutor.service.type }}
  ports:
  - port: {{ .Values.agentGuardExecutor.service.port }}
    targetPort: {{ .Values.agentGuardExecutor.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "akto-ai-guardrails.agentGuardExecutor.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.agentGuardEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto-ai-guardrails.fullname" . }}-engine
  labels:
    {{- include "akto-ai-guardrails.agentGuardEngine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agentGuardEngine.service.type }}
  ports:
  - port: {{ .Values.agentGuardEngine.service.port }}
    targetPort: {{ .Values.agentGuardEngine.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "akto-ai-guardrails.agentGuardEngine.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.guardrailsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto-ai-guardrails.fullname" . }}-service
  labels:
    {{- include "akto-ai-guardrails.guardrailsService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guardrailsService.service.type }}
  ports:
  - port: {{ .Values.guardrailsService.service.port }}
    targetPort: {{ .Values.guardrailsService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "akto-ai-guardrails.guardrailsService.selectorLabels" . | nindent 4 }}
{{- end }}
