apiVersion: v2
name: akto-mini-runtime
description: Helm chart for installing Akto hybrid runtime
type: application
version: 0.5.6
appVersion: "0.5.6"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/mini-runtime
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
