apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akto.fullname" . }}-source-code-analyser
spec:
  replicas: {{ .Values.source_code_analyser.replicas }}
  selector:
    matchLabels:
      app: {{ include "akto.fullname" . }}-source-code-analyser
  template:
    metadata:
      labels:
        app: {{ include "akto.fullname" . }}-source-code-analyser
    spec:
      containers:
      - env:
          - name: START_JAVA_LSP
            value: {{ quote .Values.source_code_analyser.codeAnalysisLspService.env.startJavaLsp }}
        image: {{ .Values.source_code_analyser.codeAnalysisService.image.repository }}:{{ .Values.source_code_analyser.codeAnalysisService.image.tag
                 | default .Chart.AppVersion }}
        volumeMounts:
          - name: source-code
            mountPath: /data
        args:
          - cli
          - extract
          - --START_JAVA_LSP={{ .Values.source_code_analyser.codeAnalysisLspService.env.startJavaLsp | quote }}

        name: code-analysis-lsp-service

      - name: eclipse-jdtls
        image: hotavneesh/eclipse-jdtls:latest
        volumeMounts:
          - name: source-code
            mountPath: /data
      - env:
          - name: SOURCE_CODE_ANALYSER
            value: {{ quote .Values.source_code_analyser.codeAnalysisService.env.sourceCodeAnalyser }}
          - name: LLM_TOKEN
            value: {{ quote .Values.source_code_analyser.codeAnalysisService.env.llmToken }}
          - name: PORT
            value: {{ quote .Values.source_code_analyser.codeAnalysisService.env.port }}
        image: {{ .Values.source_code_analyser.codeAnalysisService.image.repository }}:{{ .Values.source_code_analyser.codeAnalysisService.image.tag
                 | default .Chart.AppVersion }}
        volumeMounts:
          - name: source-code
            mountPath: /data
        args:
          - cli
          - extract
          - --SOURCE_CODE_ANALYSER={{ .Values.source_code_analyser.codeAnalysisService.env.sourceCodeAnalyser | quote }}
          - --PORT={{ .Values.source_code_analyser.codeAnalysisService.env.port | int }}

        name: code-analysis-service

      - env:
        - name: BITBUCKET_HOST
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.bitbucketHost }}
        - name: BITBUCKET_TOKEN
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.bitbucketToken }}
        - name: GITHUB_ACCESS_TOKEN
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.githubAccessToken }}
        - name: DATABASE_ABSTRACTOR_SERVICE_URL
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.databaseAbstractorUrl }}
        - name: DATABASE_ABSTRACTOR_SERVICE_TOKEN
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.databaseAbstractorToken }}
        - name: SOURCE_CODE_HOST
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.sourceCodeHost}}
        - name: AKTO_MONGO_CONN
          value: {{ quote .Values.mongo.aktoMongoConn }}
        - name: IS_KUBERNETES
          value: "true"
        - name: RUNTIME_MODE
          value: {{ quote .Values.source_code_analyser.aktoSourceCodeAnalyser.env.runtimeMode}}
        - name: DOCKER_VOLUME
          value: "/data/"
        image: {{ .Values.source_code_analyser.aktoSourceCodeAnalyser.image.repository }}:{{ .Values.source_code_analyser.aktoSourceCodeAnalyser.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.source_code_analyser.aktoSourceCodeAnalyser.imagePullPolicy }}
        name: akto-source-code-analyser
        resources: {{- toYaml .Values.source_code_analyser.aktoSourceCodeAnalyser.resources |  nindent 10 }}
        volumeMounts:
          - name: source-code
            mountPath: /data
      restartPolicy: Always

      volumes:
        - name: source-code
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-source-code-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-source-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
